server:
  port: 8000

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 651849803636-evi8j0098ogv901e8fg5469con3hbcr2.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml


file:
  path: C:/junil/web-3-202210/library/upload/