server:
  port: 8000

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 651849803636-i1fg9uolev0paevo4na33jbkoh7c1bvg.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: ehdud05264@

mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:/dozero/library/upload/

